language: ruby
rvm:
  - 2.3.1
  - jruby-9.1.5.0
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
