language: ruby
rvm:
  - 2.3.1
  - 2.4.2
  - jruby-9.1.5.0
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
