language: ruby
rvm:
  - 2.3.1
  - 2.4.2
  - jruby-9.1.9.0
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
before_install:
  - gem update --system
  # TODO: recheck 2018/01/13
  # This has been commented out until the following issues are resolved
  # https://github.com/bundler/bundler/issues/6144
  # https://github.com/rubygems/rubygems/issues/2055
  # - gem update bundler
  - gem install bundler -v 1.16.0
  - gem pristine bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
