language: ruby
rvm:
  - 2.5.1
  - 2.6.1
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/ruby.gemfile
before_install:
  - gem update --system
  - gem update bundler
  - gem pristine bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
